"""OpenAI Codex runtime adapter (current project config schema).

Codex reads ``AGENTS.md`` (the generated shared manual) and optional markdown
agent files under ``.codex/agents/``.  We also emit a conservative project
``.codex/config.toml`` that blocks direct network while letting the Harness
policy own bounded AUTO/ASK/DENY decisions.
"""

from __future__ import annotations

from pathlib import Path

from . import base

CODEX_DIR = base.REPO_ROOT / ".codex"


def config_toml() -> str:
    return (
        "# Codex harness project config — generated by `harness sync`.\n"
        "# Harness owns action approval; Codex itself cannot bypass it.\n"
        'approval_policy = "never"\n'
        'sandbox_mode = "workspace-write"\n'
        "\n"
        "[sandbox_workspace_write]\n"
        "network_access = false\n"
        "\n"
        "[mcp_servers.bughunt]\n"
        f'command = "{base.REPO_ROOT / "harness"}"\n'
        'args = ["mcp", "serve"]\n'
        "required = true\n"
    )


def write_config() -> Path:
    path = CODEX_DIR / "config.toml"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(config_toml(), encoding="utf-8")
    return path


def write_agents() -> list[Path]:
    out_dir = CODEX_DIR / "agents"
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for spec in base.load_specs():
        path = out_dir / f"{spec.name}.md"
        path.write_text(spec.render("codex"), encoding="utf-8")
        written.append(path)
    return written


def sync() -> dict:
    return {
        "config": str(write_config()),
        "agents": [str(p) for p in write_agents()],
    }


__all__ = ["CODEX_DIR", "config_toml", "write_config", "write_agents", "sync"]
